"tag" = { fg = "light-red" }
"attribute" = { fg = "light-yellow" }
"comment" = { fg = "light-black" }
"constant" = { fg = "green" }
"constant.numeric" = { fg = "light-yellow" }
"constant.builtin" = { fg = "light-green" }
"constant.character.escape" = { fg = "cyan" }
"constructor" = { fg = "light-blue" }
"function" = { fg = "light-red" }
"function.builtin" = { fg = "cyan" }
"function.macro" = { fg = "light-yellow" }
"keyword" = { fg = "light-green" }
"keyword.control" = { fg = "light-cyan" }
"keyword.control.import" = { fg = "light-cyan" }
"keyword.directive" = { fg = "light-cyan" }
"keyword.storage" = { fg = "light-blue" }
"label" = { fg = "bright-white" }
"namespace" = { fg = "bright-white" }
"operator" = { fg = "bright-white" }
"keyword.operator" = { fg = "bright-white" }
"special" = { fg = "bright-white" }
"string" = { fg = "light-green" }
"type" = { fg = "light-cyan" }
"variable.builtin" = { fg = "light-yellow" }
"variable.parameter" = { fg = "bright-white" }
"variable.other.member" = { fg = "bright-white" }

"markup.heading" = { fg = "red" }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-purple", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.list" = { fg = "light-red" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"]}
"markup.link.text" = { fg = "purple" }

"diff.plus" = "light-green"
"diff.delta" = "purple"
"diff.minus" = "red"

"diagnostic.info".underline = { color = "blue", style = "curl" } 
"diagnostic.hint".underline = { color = "green", style = "curl" } 
"diagnostic.warning".underline = { color = "yellow", style = "curl" } 
"diagnostic.error".underline = { color = "red", style = "curl" } 
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }

"ui.virtual" = { fg = "black" }
"ui.virtual.indent-guide" = { fg = "light-black" }
"ui.virtual.whitespace" = { fg = "light-black" }
"ui.virtual.ruler" = { bg = "black" }
"ui.virtual.inlay-hint" = { fg = "white" }
"ui.virtual.jump-label" = { fg = "white", modifiers = ["bold"] }

"ui.cursor" = { fg = "bright-white", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "bright-white", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "bight-white", modifiers = ["underlined"]}

"ui.selection" = { bg = "blue" }
"ui.selection.primary" = { bg = "purple" }
"ui.cursorline.primary" = { bg = "black" }

"ui.highlight" = { bg = "light-black" }
"ui.highlight.frameline" = {}

"ui.linenr" = { fg = "blue" }
"ui.linenr.selected" = { fg = "white" }

"ui.statusline" = { fg = "bright-white", bg="black" }
"ui.statusline.inactive" = { fg = "white" }
"ui.statusline.normal" = { fg = "white", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "white", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "white", modifiers = ["bold"] }

"ui.bufferline" = { fg = "cyan", bg = "black" }
"ui.bufferline.active" = { fg = "light-cyan", bg = "light-black", underline = { color = "black", style = "line" } }
"ui.bufferline.background" = { bg = "black" }

"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "bright-white", bg = "black", modifiers = ["bold"] }

"ui.help" = { fg = "white", bg = "black" }
"ui.popup" = { bg = "black" }
"ui.window" = { fg = "black" }
"ui.menu" = { fg = "bright-white", bg = "black" }
"ui.menu.selected" = { fg = "black", bg = "blue" }
"ui.menu.scroll" = { fg = "white", bg = "black" }

"ui.debug" = { fg = "light-red" }

[palette]
background="#080703"
foreground="#DAE3EB"

black="#0F2733"
light-black="#1B465C"
red="#694D39"
light-red="#997154"
green="#5EA331"
light-green="#9DC489"
yellow="#CC6114"
light-yellow="#DAED61"
blue="#2B5A73"
light-blue="#3A7899"
purple="#52314C"
light-purple="#73456B"
cyan="#57849C"
light-cyan="#74B0CF"
white="#9EA5AB"
bright-white="#DAE3EB"
